# This file was auto-generated by Fern from our API Definition.

import typing
from .user_message import UserMessage
from .assistant_message import AssistantMessage
from .system_message import SystemMessage
from .tool_message import ToolMessage

ChatMessage = typing.Union[UserMessage, AssistantMessage, SystemMessage, ToolMessage]
