version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"


python:
  install:
    # Install our python package before building the docs
    - method: pip
      path: .
    # Install theme
    - requirements: docs/requirements.txt  
