# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .batch import Batch


class ListBatchesResponse(UncheckedBaseModel):
    """
    Response to a request to list batches.
    """

    batches: typing.Optional[typing.List[Batch]] = pydantic.Field(default=None)
    """
    The batches that belong to the authenticated user.
    """

    next_page_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    A token, which can be sent as `page_token` to retrieve the next page.
    If this field is omitted, there are no subsequent pages.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
