# This file was auto-generated by Fern from our API Definition.

from ..core.api_error import ApiError
from ..types.gateway_timeout_error_body import GatewayTimeoutErrorBody


class GatewayTimeoutError(ApiError):
    def __init__(self, body: GatewayTimeoutErrorBody):
        super().__init__(status_code=504, body=body)
