# This file was auto-generated by Fern from our API Definition.

from ..core.api_error import ApiError
from ..types.too_many_requests_error_body import TooManyRequestsErrorBody


class TooManyRequestsError(ApiError):
    def __init__(self, body: TooManyRequestsErrorBody):
        super().__init__(status_code=429, body=body)
