# This file was auto-generated by Fern from our API Definition.

from ..core.api_error import ApiError
from ..finetuning.finetuning.types.error import Error


class UnauthorizedError(ApiError):
    def __init__(self, body: Error):
        super().__init__(status_code=401, body=body)
