# This file was auto-generated by Fern from our API Definition.

import typing

ChatFinishReason = typing.Union[
    typing.Literal["COMPLETE", "STOP_SEQUENCE", "MAX_TOKENS", "TOOL_CALL", "ERROR"], typing.Any
]
