# This file was auto-generated by Fern from our API Definition.

import typing

ClassifyResponseClassificationsItemClassificationType = typing.Union[
    typing.AnyStr, typing.Literal["single-label", "multi-label"]
]
