# This file was auto-generated by Fern from our API Definition.

import typing

CompatibleEndpoint = typing.Union[
    typing.AnyStr, typing.Literal["chat", "embed", "classify", "summarize", "rerank", "rate", "generate"]
]
