# This file was auto-generated by Fern from our API Definition.

import typing

EmbedRequestEmbeddingTypesItem = typing.Union[
    typing.AnyStr, typing.Literal["float", "int8", "uint8", "binary", "ubinary"]
]
