# This file was auto-generated by Fern from our API Definition.

import typing

EmbedJobStatus = typing.Union[typing.Literal["processing", "complete", "cancelling", "cancelled", "failed"], typing.Any]
