# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore


class ModelConfig(pydantic.BaseModel):
    route: str
    name: str
    billing_model_name: typing.Optional[str] = None
    model_id: typing.Optional[str] = None
    model_size: typing.Optional[str] = None
    finetune_id: typing.Optional[str] = None
    endpoint_type: typing.Optional[str] = None
    model_type: typing.Optional[str] = None
    nemo_model_id: typing.Optional[str] = None
    model_url: typing.Optional[str] = None
    context_length: typing.Optional[int] = None
    serving_framework: typing.Optional[str] = None
    serving_entrypoint: typing.Optional[str] = None
    compatible_endpoints: typing.Optional[typing.List[str]] = None
    prompt_templates: typing.Optional[typing.Dict[str, str]] = None
    compression_values: typing.Optional[typing.Dict[str, float]] = None
    compatibility_version: typing.Optional[int] = None
    default_language: typing.Optional[str] = None
    additional_languages: typing.Optional[str] = None
    labels: typing.Optional[typing.List[str]] = None
    multi_label: typing.Optional[bool] = None
    baseline_model: typing.Optional[str] = None
    is_baseline: typing.Optional[bool] = None
    tokenizer_id: typing.Optional[str] = None
    end_of_sequence_string: typing.Optional[str] = None
    streaming: typing.Optional[bool] = None
    group: typing.Optional[str] = None
    model_version: typing.Optional[str] = None

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        extra = pydantic.Extra.allow
        json_encoders = {dt.datetime: serialize_datetime}
