# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .parse_markdown_page import ParseMarkdownPage


class ParseMarkdownPageVariant(UncheckedBaseModel):
    """
    A parsed page with markdown content.
    """

    index: int = pydantic.Field()
    """
    Zero-based page index.
    """

    markdown: ParseMarkdownPage

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
