# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .parse_bounding_box import ParseBoundingBox
from .parse_bounding_box_normalized import ParseBoundingBoxNormalized
from .parse_image_category import ParseImageCategory


class ParseImageBlock(UncheckedBaseModel):
    """
    Payload for an image block.
    """

    id: str = pydantic.Field()
    """
    Unique identifier for the image within the page (for example `img-0`).
    """

    description: str = pydantic.Field()
    """
    Model-generated description of the image.
    """

    category: ParseImageCategory
    bounding_box: ParseBoundingBox
    bounding_box_normalized: ParseBoundingBoxNormalized

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
