# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .parse_block import ParseBlock


class ParseBlocksPageVariant(UncheckedBaseModel):
    """
    A parsed page with structured content blocks.
    """

    index: int = pydantic.Field()
    """
    Zero-based page index.
    """

    blocks: typing.List[ParseBlock] = pydantic.Field()
    """
    Ordered content blocks extracted from the page.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
