# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel, UnionMetadata
from .parse_block import ParseBlock
from .parse_markdown_page import ParseMarkdownPage


class BlocksParsePage(UncheckedBaseModel):
    """
    A single parsed page. The payload shape depends on `output_format`.
    """

    type: typing.Literal["blocks"] = "blocks"
    index: int
    blocks: typing.List[ParseBlock]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow


class MarkdownParsePage(UncheckedBaseModel):
    """
    A single parsed page. The payload shape depends on `output_format`.
    """

    type: typing.Literal["markdown"] = "markdown"
    index: int
    markdown: ParseMarkdownPage

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow


ParsePage = typing_extensions.Annotated[
    typing.Union[BlocksParsePage, MarkdownParsePage], UnionMetadata(discriminant="type")
]
