# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .parse_bounding_box import ParseBoundingBox
from .parse_bounding_box_normalized import ParseBoundingBoxNormalized
from .parse_table_content_type import ParseTableContentType


class ParseTableBlock(UncheckedBaseModel):
    """
    Payload for a table block.
    """

    type: ParseTableContentType = "html"
    html: str = pydantic.Field()
    """
    Table content as HTML.
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional table title when detected.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional table description when detected.
    """

    bounding_box: ParseBoundingBox
    bounding_box_normalized: ParseBoundingBoxNormalized

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
