# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .api_meta import ApiMeta
from .parse_page import ParsePage


class ParseResponse(UncheckedBaseModel):
    """
    Response from the v2 parse endpoint.
    """

    id: str = pydantic.Field()
    """
    Unique identifier for the parse response.
    """

    pages: typing.List[ParsePage] = pydantic.Field()
    """
    Parsed pages in document order.
    """

    meta: typing.Optional[ApiMeta] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
