# This file was auto-generated by Fern from our API Definition.

import typing
from .system_message_content_item import SystemMessageContentItem

SystemMessageContent = typing.Union[str, typing.List[SystemMessageContentItem]]
