# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
import typing
from .v2tool_call_function import V2ToolCallFunction
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class V2ToolCall(UncheckedBaseModel):
    """
    A array of tool calls to be made.
    """

    id: typing.Optional[str] = None
    type: typing.Optional[typing.Literal["function"]] = None
    function: typing.Optional[V2ToolCallFunction] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
