# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
import typing
from .v2tool_function import V2ToolFunction
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class V2Tool(UncheckedBaseModel):
    type: typing.Optional[typing.Literal["function"]] = None
    function: typing.Optional[V2ToolFunction] = pydantic.Field(default=None)
    """
    The function to be executed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
