# This file was auto-generated by Fern from our API Definition.

from ...core.api_error import ApiError
from ..types.forbidden_error_body import ForbiddenErrorBody


class ForbiddenError(ApiError):
    def __init__(self, body: ForbiddenErrorBody):
        super().__init__(status_code=403, body=body)
