# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
from .chat_stream_event_event_type import ChatStreamEventEventType
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class ChatStreamEvent(UncheckedBaseModel):
    event_type: ChatStreamEventEventType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
