# This file was auto-generated by Fern from our API Definition.

import typing

CompatibleEndpoint = typing.Union[
    typing.Literal["chat", "embed", "classify", "summarize", "rerank", "rate", "generate"], typing.Any
]
