# This file was auto-generated by Fern from our API Definition.

import typing

GenerateStreamEventEventType = typing.Union[typing.Literal["text-generation", "stream-end", "stream-error"], typing.Any]
